### ISSUE TITLE
send2phone推送建议新增wxpusher   

### ISSUE THREAD

**Issue by gaows20** [q123458384/qiandao#8]
站内信显示很方便，不需要像severchan一样点进去查看
地址：http://wxpusher.zjiecode.com/demo/

get请求
推送方式http://wxpusher.zjiecode.com/api/send/message/?appToken=XXX&content=YYY&uid=ZZZ

**Comment by crossgg** [comment]
> 站内信显示很方便，不需要像severchan一样点进去查看
> 地址：http://wxpusher.zjiecode.com/demo/
> 
> get请求
> 推送方式http://wxpusher.zjiecode.com/api/send/message/?appToken=XXX&content=YYY&uid=ZZZ

已经帮你向大佬反馈了~大佬说会更新
大佬的更新地址：https://github.com/AragonSnow/qiandao
